theme: night
paths:
  - path: labs
preview_tags:
  start: |
    <div style="background: white; color: black; padding: 10px 5px; font-size: 0.5em; border: 5px solid lightgray; position: relative;">
    <p style="background: #333; padding: 3px 5px; color: #eee; font-size: 0.5em; position: absolute; top: -1px; left: 0px; margin: 0; text-transform: uppercase">Preview</p>
  end: '</div>'
