name: Deploy

on:
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: npm
        run: npm install
      - name: Build
        run: ./build

      - name: Configure git
        run: |
          git config user.name "Deploy Bot"
          git config user.email "<>"

      - name: Timestamp
        id: timestamp
        run: echo "::set-output name=value::$(date +'%Y-%m-%dT%H:%M:%S')"

      - name: Create deploy branch
        if: '[ -z "git show-ref refs/heads/gh-pages" ]'
        run: git checkout -b gh-pages

      - name: Commit & push
        run: |
          mv dist/ public/
          git add public
          git commit -m '[Deploy] {{ steps.timestamp.outputs.value }}'
          git push origin gh-pages -f
